import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import Image from "next/image";
import { ThemeProvider } from "~/components/theme-provider";

import { GeistSans } from "geist/font/sans";
import { Toaster } from "~/components/ui/sonner";

import TopNav from "~/_Components/NavBar";
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
import { ClerkProvider } from "@clerk/nextjs";

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <div className="flex items-center justify-center">
            {/* <PageLayout> */}
            <TopNav></TopNav>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              {modal}
            </ThemeProvider>
            <Toaster />
            {/* </PageLayout> */}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
